name: Python CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Setting up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installing flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Linting with flake8
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203,E501 --show-source --statistics
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Setting up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
      - name: Running tests with pytest
        run: |
          pytest tests/ --cov=./ --cov-report=xml
        env:
          PYTHONPATH: .
      - name: Uploading coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
