name: Python CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Setting up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov flake8

      - name: Linting with flake8
        run: |
          flake8 . --max-line-length=79 --extend-ignore=E203 --show-source --statistics

      - name: Running tests with pytest
        run: |
          pytest tests/ --cov=./ --cov-report=xml
        env:
          PYTHONPATH: .

      - name: Uploading coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
