name: Python CI

on:
  push:
    branches: [main, task-1, task-2]
  pull_request:
    branches: [main, task-1, task-2]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Setting up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Installing test-specific packages
          pip install pytest pytest-cov flake8

      - name: Linting with flake8
        run: |
          flake8 . --max-line-length=79 --extend-ignore=E203 --show-source --statistics

      - name: Running tests with pytest
        run: |
          pytest tests/ --cov=./ --cov-report=xml
        env:
          PYTHONPATH: .

      - name: Uploading coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
